=== FLOIP/flow-builder/_tmp/flowSpecJsonSchema.json
{
  "$ref": "#/definitions/IContainer",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "IBlock": {
      "additionalProperties": false,
      "description": "Block Structure: https://floip.gitbook.io/flow-specification/flows#blocks",
      "properties": {
        "config": {
          "description": "Additional parameters that are specific to the type of the block. Details are provided within the Block documentation.",
          "type": "object"
        },
        "exits": {
          "description": "a list of all the exits for the block. Exits must contain the required keys below, and can contain additional keys based on the Block type",
          "items": {
            "$ref": "#/definitions/IBlockExit"
          },
          "type": "array"
        },
        "label": {
          "description": "A human-readable free-form description for this Block.",
          "type": "string"
        },
        "name": {
          "description": "A human-readable \"variable name\" for this block. This must be restricted to word characters so that it can be used as a variable name in expressions. When blocks write results output, they write to a variable corresponding the name of the block.",
          "type": "string"
        },
        "semantic_label": {
          "description": "A user-controlled field that can be used to code the meaning of the data collected by this block in a standard taxonomy or coding system, * e.g.: a FHIR ValueSet, an industry-specific coding system like SNOMED CT, or an organization's internal taxonomy service. (e.g. \"SNOMEDCT::Gender finding\")",
          "type": "string"
        },
        "type": {
          "description": "A specific string designating the type or \"subclass\" of this Block. This must be one of the Block type names within the specification, such as Core.RunFlow or MobilePrimitives.Message.",
          "type": "string"
        },
        "uuid": {
          "description": "A globally unique identifier for this Block.  (See UUID Format: https://floip.gitbook.io/flow-specification/flows#uuid-format)",
          "type": "string"
        },
        "vendor_metadata": {
          "description": "A set of key-value elements that is not controlled by the Specification, but could be relevant to a specific vendor/platform/implementation.",
          "type": "object"
        }
      },
      "required": [
        "uuid",
        "name",
        "type",
        "exits"
      ],
      "type": "object"
    },
    "IBlockExit": {
      "additionalProperties": false,
      "description": "Block Exit: https://floip.gitbook.io/flow-specification/flows#exit-node-specification",
      "properties": {
        "config": {
          "description": "This contains additional information required for each mode supported by the block. Details are provided within the Block documentation",
          "type": "object"
        },
        "default": {
          "description": "If this key is present and true, the exit is treated as the flow-through default in a case evaluation. The block will terminate through this exit if no test expressions in other exits evaluate true..",
          "type": "boolean"
        },
        "destination_block": {
          "description": "This is the uuid of the Block this exit connects to. It can be null if the exit does not connect to a block (if it is the final block).",
          "type": "string"
        },
        "label": {
          "description": "This is the human-readable name of the exit (as a translated resource ID), which might be presented to a contact.",
          "type": "string"
        },
        "semantic_label": {
          "description": "A user-controlled field that can be used to code the meaning of the data collected by this block in a standard taxonomy or coding system, e.g.: a FHIR ValueSet, an industry-specific coding system like SNOMED CT, or an organization's internal taxonomy service. (e.g. \"SNOMEDCT::Feminine Gender\")",
          "type": "string"
        },
        "tag": {
          "description": "This is an identifier for the exit, suitable for use as a variable name in rolling up results (e.g.: \"male\"). It does not need to be unique within the block; multiple exits may be tagged the same. (Some authoring tools may choose to auto-generate the tag from the label's primary language, to avoid usability problems with these getting out of sync.) Word characters only.",
          "type": "string"
        },
        "test": {
          "description": "For blocks that evaluate conditions, this is an expression that determines whether this exit will be selected as the path out of the block. The first exit with an expression that evaluates to a \"truthy\" value will be chosen.",
          "type": "string"
        },
        "uuid": {
          "description": "A globally unique identifier for this Block.  (See UUID Format: https://floip.gitbook.io/flow-specification/flows#uuid-format)",
          "type": "string"
        }
      },
      "required": [
        "uuid",
        "label",
        "tag",
        "config"
      ],
      "type": "object"
    },
    "IContainer": {
      "additionalProperties": false,
      "description": "Flow Containers hold a group of related Flows: https://floip.gitbook.io/flow-specification/flows#flows",
      "properties": {
        "description": {
          "description": "An extended human-readable description of the content.",
          "type": "string"
        },
        "flows": {
          "description": "A list of the Flows within the Container (see below)",
          "items": {
            "$ref": "#/definitions/IFlow"
          },
          "type": "array"
        },
        "name": {
          "description": "A human-readable name for the Container content.",
          "type": "string"
        },
        "resources": {
          "description": "A set of the Resources needed for executing the Flows in the Container, keyed by resource uuid.",
          "items": {
            "$ref": "#/definitions/IResource"
          },
          "type": "array"
        },
        "specification_version": {
          "description": "The version of the Flow Spec that this package is compliant with, e.g. 1.0.0-rc1",
          "type": "string"
        },
        "uuid": {
          "description": "A globally unique identifier for this Container.  (See UUID Format: https://floip.gitbook.io/flow-specification/flows#uuid-format)",
          "type": "string"
        },
        "vendor_metadata": {
          "description": "A set of key-value elements that is not controlled by the Specification, but could be relevant to a specific vendor/platform/implementation.",
          "type": "object"
        }
      },
      "required": [
        "specification_version",
        "uuid",
        "name",
        "flows",
        "resources"
      ],
      "type": "object"
    },
    "IFlow": {
      "additionalProperties": false,
      "description": "Flow structure: https://floip.gitbook.io/flow-specification/flows#flows",
      "properties": {
        "blocks": {
          "description": "A list of the Blocks in the flow.",
          "items": {
            "$ref": "#/definitions/IBlock"
          },
          "type": "array"
        },
        "exit_block_id": {
          "description": "If provided, the ID of the block in blocks that will be jumped to if there is an error or deliberate exit condition during Flow Run. If not provided, the Flow Run will end immediately.",
          "type": "string"
        },
        "first_block_id": {
          "description": "The ID of the block in blocks that is at the beginning of the flow.",
          "type": "string"
        },
        "interaction_timeout": {
          "description": "The number of seconds of inactivity after which Contact input for this flow is no longer accepted, and Runs in progress are terminated",
          "type": "number"
        },
        "label": {
          "description": "An extended user-provided description for the flow.",
          "type": "string"
        },
        "languages": {
          "description": "A list of the languages that the Flow has suitable content for. See language object specification: https://floip.gitbook.io/flow-specification/flows#language-objects-and-identifiers.",
          "items": {
            "$ref": "#/definitions/ILanguage"
          },
          "type": "array"
        },
        "last_modified": {
          "description": "The time when this flow was last modified, in UTC, with microsecond precision: \"2016-12-25 13:42:05.234598\"",
          "type": "string"
        },
        "name": {
          "description": "A human-readable name for the Flow content",
          "type": "string"
        },
        "supported_modes": {
          "description": "A list of the supported Modes that the Flow has content suitable for.",
          "items": {
            "$ref": "#/definitions/SupportedMode"
          },
          "type": "array"
        },
        "uuid": {
          "description": "A globally unique identifier for this Flow.  (See UUID Format: https://floip.gitbook.io/flow-specification/flows#uuid-format)",
          "type": "string"
        },
        "vendor_metadata": {
          "description": "A set of key-value elements that is not controlled by the Specification, but could be relevant to a specific vendor/platform/implementation.",
          "type": "object"
        }
      },
      "required": [
        "uuid",
        "name",
        "last_modified",
        "interaction_timeout",
        "supported_modes",
        "languages",
        "blocks",
        "first_block_id"
      ],
      "type": "object"
    },
    "ILanguage": {
      "additionalProperties": false,
      "description": "Language descriptor used within Flows and Resources: https://floip.gitbook.io/flow-specification/flows#language-objects-and-identifiers",
      "properties": {
        "bcp_47": {
          "description": "The BCP 47 locale code for this language, e.g. \"en-GB\". These codes are often useful in conjunction with speech synthesis and speech recognition tools.",
          "type": "string"
        },
        "id": {
          "description": "Language Identifier, e.g. \"eng-female\", described in https://floip.gitbook.io/flow-specification/flows#language-identifiers",
          "type": "string"
        },
        "iso_639_3": {
          "description": "ISO 639-3 code for the language. This is a 3-letter string, e.g. \"eng\". \"mis\" is the ISO 639-3 code for languages not yet included in ISO 639-3.",
          "type": "string"
        },
        "label": {
          "description": "Human-readable description for this language and variant.",
          "type": "string"
        },
        "variant": {
          "description": "Where multiple languages/content sets are used with the same ISO 639-3 code, variant describes the specialization, e.g. \"east_africa\".",
          "type": "string"
        }
      },
      "required": [
        "id",
        "iso_639_3"
      ],
      "type": "object"
    },
    "IResource": {
      "additionalProperties": false,
      "properties": {
        "uuid": {
          "type": "string"
        },
        "values": {
          "items": {
            "$ref": "#/definitions/IResourceValue"
          },
          "type": "array"
        }
      },
      "required": [
        "uuid",
        "values"
      ],
      "type": "object"
    },
    "IResourceValue": {
      "additionalProperties": false,
      "properties": {
        "content_type": {
          "type": "string"
        },
        "language_id": {
          "type": "string"
        },
        "mime_type": {
          "type": "string"
        },
        "modes": {
          "items": {
            "$ref": "#/definitions/SupportedMode"
          },
          "type": "array"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "language_id",
        "content_type",
        "modes",
        "value"
      ],
      "type": "object"
    },
    "SupportedMode": {
      "description": "Supported modes for Flows and Resources: https://floip.gitbook.io/flow-specification/flows#modes",
      "enum": [
        "TEXT",
        "SMS",
        "USSD",
        "IVR",
        "RICH_MESSAGING",
        "OFFLINE"
      ],
      "type": "string"
    }
  }
}

=== FLOIP/flow-builder/src/store/builder/5b8c87d6-de90-4bc4-8668-4f040000006e-flow-block-group.json
{
  "specification_version": "1.0.10",
  "uuid": "3666a05d-3792-482b-8f7f-9e2472e4f027",
  "name": "container name",
  "description": "container description",
  "vendor_metadata": {},
  "flows": [
    {
      "uuid": "463580a6-ff3a-4e43-a2be-4265cc33dd91",
      "name": "Test",
      "label": "Test",
      "last_modified": "2021-06-10T11:19:05.790Z",
      "interaction_timeout": 30,
      "vendor_metadata": {},
      "supported_modes": [
        "SMS",
        "USSD",
        "IVR"
      ],
      "languages": [
        {
          "id": "22",
          "label": "English",
          "iso_639_3": "eng"
        }
      ],
      "first_block_id": "31570470-cb83-436a-97d6-5a0ce471280e",
      "blocks": [
        {
          "uuid": "31570470-cb83-436a-97d6-5a0ce471280e",
          "vendor_metadata": {
            "io_viamo": {
              "uiData": {
                "xPosition": 390,
                "yPosition": 275
              }
            }
          },
          "type": "Core.SetContactProperty",
          "name": "abc",
          "label": "",
          "semantic_label": "",
          "config": {
            "set_contact_property": {
              "property_key": "name_3",
              "property_value": ""
            }
          },
          "exits": [
            {
              "uuid": "e41f9b81-165f-4fa7-9c93-7870d93ae5c4",
              "tag": "Default",
              "label": "Default",
              "default": true,
              "config": {}
            }
          ]
        },
        {
          "uuid": "bc3da62c-f036-4ec6-b157-5c43ac44b3db",
          "vendor_metadata": {
            "io_viamo": {
              "uiData": {
                "xPosition": 844,
                "yPosition": 250
              }
            }
          },
          "type": "Core.SetGroupMembership",
          "name": "def",
          "label": "",
          "semantic_label": "",
          "config": {
            "group_key": 988,
            "group_name": "Group 3",
            "is_member": null
          },
          "exits": [
            {
              "uuid": "c0152ecc-bd8b-465a-9fd7-58c8039cca96",
              "tag": "Default",
              "label": "Default",
              "default": true,
              "config": {}
            }
          ]
        }
      ],
      "first_block_id": "31570470-cb83-436a-97d6-5a0ce471280e"
    }
  ],
  "resources": [
    {
      "uuid": "7aa63f91-1eeb-466b-a27d-4fdee496a2e9",
      "values": []
    },
    {
      "uuid": "ecb48341-5134-4a34-a75f-004fd976b369",
      "values": []
    }
  ]
}
